services:
  db:
    image: mysql:8.0
    container_name: gestion-notes-db
    restart: always
    environment:
      MYSQL_DATABASE: GestionNotes
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: gestion-notes-app
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/GestionNotes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      db:
        condition: service_healthy
