services:
  app:
    build: .
    container_name: gestion-notes-app
    restart: on-failure
    ports:
      - "8082:8082"
    labels:
      - "coolify.managed=true"
      - "coolify.application=true"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://nozomi.proxy.rlwy.net:34064/GestionNotes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ZGvFilnIzKUTHKgoVLKuIGcnaiHkwsSE
